services:
  app:
    build: .
    command: python3 src/main.py
    volumes:
      - .:/app
    tty: true
    stdin_open: true
  api:
    build: .
    command: python3 src/api.py
    volumes:
      - .:/api
    tty: true
    stdin_open: true